services:
  warg-server:
    image: "ghcr.io/reecepbcups/warg-registry:${WARG_REGISTRY_DOCKER_TAG:-v0.9.3}"
    container_name: "warg-server"
    platform: linux/amd64
    environment:
      WARG_OPERATOR_KEY: ecdsa-p256:I+UlDo0HxyBBFeelhPPWmD+LnklOpqZDkrFP5VduASk=
      WARG_NAMESPACE: wavstools
      WKG_REGISTRY: http://localhost:5000
      WARG_CONTENT_BASE_URL: http://localhost:8090
      WARG_LISTEN: 0.0.0.0:8090
      WARG_VERBOSE: 1
    ports:
      - 8090:8090
    command: ["--rm"]

  ipfs:
    image: ipfs/kubo:v0.35.0
    container_name: ipfs
    network_mode: host
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "8080:8080"
      - "5001:5001"
    stop_signal: SIGKILL
    command: daemon
    restart: unless-stopped
