[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solidity_version = '0.8.22'
evm_version = 'shanghai'
# via_ir = true
ffi = false # false by default for security reasons
fs_permissions = [{ access = "read-write", path = "./" },]

remappings = [
  "forge-std=lib/forge-std/src/",
  "@openzeppelin=lib/openzeppelin-contracts/contracts/",
  "@wavs=node_modules/@wavs/solidity/contracts/",
]
