# This is mostly just a convenience to start common tasks from the root directory
version: "3"

silent: true

dotenv: [".env"]

includes:
  backend: ./taskfile/backend.yml
  cli: ./taskfile/cli.yml
  middleware: ./taskfile/middleware.yml
  component: ./taskfile/component.yml

tasks:
  default:
    cmds:
      - task --list-all

  clean:
    cmds:
      # Clean up all projects by running `task clean` in each project directory
      - |
        for dir in projects/*/; do
          if [ -d "$dir" ]; then
            echo "Cleaning $dir"
            cd "$dir"
            task clean
            cd "{{.REPO_ROOT}}"
          fi
        done

  setup:
    cmds:
      - npm install
      - cd tests && npm install
      - task: cli:build-abi

  setup-ci:
    vars:
      BUILD_ABI: "{{.BUILD_ABI | default true}}"
    cmds:
      - npm ci
      - cd tests && npm ci
      - task: cli:build-abi-ci
        vars:
          BUILD_ABI: "{{.BUILD_ABI}}"

  test:
    dir: tests
    cmds:
      - npm run test:report

  test:report:
    dir: tests
    cmds:
      - npm run test:report:open

  lint:
    cmds:
      - cargo fmt --all -- --check
      - cargo fix --allow-dirty --allow-staged
      - cargo clippy --all-targets -- -D warnings
