version: "3"

vars:
  COMPONENTS_DIR: "./components"
  RPC_URL: "127.0.0.1:8545"
  MIDDLEWARE_DOCKER_IMAGE: "ghcr.io/lay3rlabs/wavs-middleware:0.4.0-rc"
  SUDO:
    sh: |
      if groups | grep -q docker; then echo ""; else echo "sudo"; fi
  WAVS_CMD:
    sh: |
      ENV_FLAG=""
      if test -f {{.ENV_FILE}}; then
        ENV_FLAG="--env-file ./{{.ENV_FILE}}"
      fi
      echo "{{.SUDO}} docker run --rm --network host $ENV_FLAG -v $(pwd):/data {{.WAVS_DOCKER_IMAGE}} wavs-cli"

includes:
  avs_sync: ./avs_sync/Taskfile.yml

tasks:
  up:
    desc: Start all services with Docker Compose
    cmds:
      - docker compose up -d

  down:
    desc: Stop and remove all services
    cmds:
      - docker compose down

  restart:
    desc: Restart all services
    cmds:
      - task: down
      - task: up

  wavs-middleware:
    desc: Run any wavs middleware command
    cmds:
      - |
        docker run --rm --network host \
          --env-file .env \
          {{if .WAVS_SERVICE_MANAGER_ADDRESS}}-e WAVS_SERVICE_MANAGER_ADDRESS={{.WAVS_SERVICE_MANAGER_ADDRESS}}{{end}} \
          {{if .PAST_BLOCKS}}-e PAST_BLOCKS={{.PAST_BLOCKS}}{{end}} \
          -v ./.nodes:/root/.nodes \
          {{.MIDDLEWARE_DOCKER_IMAGE}} {{.CLI_ARGS}}
