# This is just a convenience to start common tasks from the root directory
version: "3"

# silent: true

dotenv: [".env"]

includes:
  backend: ./taskfile/backend.yml
  cli: ./taskfile/cli.yml
  middleware: ./taskfile/middleware.yml
  utils: ./taskfile/utils.yml

tasks:
  default:
    cmds:
      - task --list-all
