# This is just a convenience to start common tasks from the root directory
version: "3"

# silent: true

dotenv: ['.env']

includes:
  backend: ./backend/Taskfile.yml
  cli: ./Taskfile-cli.yml
  middleware: ./Taskfile-middleware.yml

tasks:
  default:
    cmds:
      - task --list-all