# This is mostly just a convenience to start common tasks from the root directory
version: "3"

silent: true

dotenv: [".env"]

includes:
  backend: ./taskfile/backend.yml
  cli: ./taskfile/cli.yml
  middleware: ./taskfile/middleware.yml
  component: ./taskfile/component.yml
  publish:
    taskfile: ./taskfile/publish.yml
    flatten: true

tasks:
  default:
    cmds:
      - task --list-all

  clean:
    desc: "Clean up all project artifacts and build outputs"
    vars:
      PROJECTS:
        sh: find {{.REPO_ROOT}}/projects -mindepth 1 -maxdepth 1 -type d -printf '%f\n'
    cmds:
      - for: { var: PROJECTS, split: "\n" }
        task: clean-project
        vars:
          PROJECT: "{{.ITEM}}"

  clean-project:
    desc: "Clean a specific project"
    requires:
      vars: [PROJECT]
    dir: "{{.REPO_ROOT}}/projects/{{.PROJECT}}"
    cmds:
      - task clean

  setup:
    desc: "Initialize project dependencies and build ABI files"
    cmds:
      - bun install
      - cd tests && bun install
      - task: cli:build-abi

  setup-ci:
    desc: "Initialize project dependencies for CI environment"
    vars:
      BUILD_ABI: "{{.BUILD_ABI | default true}}"
    cmds:
      - bun install --frozen-lockfile
      - cd tests && bun install --frozen-lockfile
      - task: cli:build-abi-ci
        vars:
          BUILD_ABI: "{{.BUILD_ABI}}"

  test:
    desc: "Run test suite and generate report"
    dir: tests
    cmds:
      - bun run test:report

  test:report:
    desc: "Open test report in browser"
    dir: tests
    cmds:
      - bun run test:report:open

  lint:
    desc: "Run code formatting and linting checks"
    cmds:
      - cargo fmt --all -- --check
      - cargo fix --allow-dirty --allow-staged
      - cargo clippy --all-targets -- -D warnings
