# This is mostly just a convenience to start common tasks from the root directory
version: "3"

silent: true

dotenv: [".env"]

includes:
  backend: ./taskfile/backend.yml
  cli: ./taskfile/cli.yml
  middleware: ./taskfile/middleware.yml

tasks:
  default:
    cmds:
      - task --list-all

  setup:
    cmds:
      - npm install
      - cd tests && npm install
      - task: cli:build-eigenlayer-abi

  test:
    dir: tests
    cmds:
      - npm run test 

  test:report:
    dir: tests
    cmds:
      - npm run test:report:open