services:
  anvil:
    container_name: "anvil"
    image: "${COMPOSE_FOUNDRY_DOCKER_IMAGE}"
    stop_signal: SIGKILL
    network_mode: "host"
    command: ["anvil --fork-url ${COMPOSE_ANVIL_FORK_URL} --port ${COMPOSE_ANVIL_PORT}"]

  wavs:
    container_name: "wavs"
    image: "${COMPOSE_WAVS_DOCKER_IMAGE}"
    stop_signal: SIGKILL
    network_mode: "host"
    env_file: "../.env"
    command: ["wavs", "--home", "/wavs-home"]
    volumes:
      - "${COMPOSE_WAVS_HOME}:/wavs-home"

  aggregator:
    container_name: "wavs-aggregator"
    image: "${COMPOSE_WAVS_DOCKER_IMAGE}"
    depends_on: ["wavs"]
    stop_signal: SIGKILL
    env_file: "../.env"
    command: ["wavs-aggregator", "--home", "/wavs-home"]
    volumes:
      - "${COMPOSE_WAVS_HOME}:/wavs-home"
    network_mode: "host"

  jaeger:
    container_name: wavs-jaeger
    depends_on: ["wavs"]
    image: "${COMPOSE_JAEGER_DOCKER_IMAGE}"
    network_mode: "host"
    stop_signal: SIGKILL
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    # ports managed by host network mode

  # Prometheus is used to display metrics
  prometheus:
    container_name: wavs-prometheus
    depends_on: ["wavs"]
    image: "${COMPOSE_PROMETHEUS_DOCKER_IMAGE}" 
    network_mode: "host"
    stop_signal: SIGKILL
    # ports managed by host network mode
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-otlp-receiver"
