name: "wavs-aggregator"
services:
  aggregator:
    container_name: "wavs-aggregator"
    image: "${COMPOSE_WAVS_DOCKER_IMAGE}"
    stop_signal: SIGKILL
    env_file: "../.env"
    command: ["wavs-aggregator", "--home", "/wavs-home", "--port", "${COMPOSE_WAVS_AGGREGATOR_PORT:-8200}"]
    volumes:
      - "${COMPOSE_WAVS_HOME}:/wavs-home"
    network_mode: "host"