name: "wavs"
services:
  wavs:
    container_name: "wavs"
    image: "${COMPOSE_WAVS_DOCKER_IMAGE}"
    stop_signal: SIGKILL
    network_mode: "host"
    env_file: "../.env"
    command: ["wavs", "--home", "/wavs-home"]
    volumes:
      - "${COMPOSE_WAVS_HOME}:/wavs-home"

  aggregator:
    container_name: "wavs-aggregator"
    image: "${COMPOSE_WAVS_DOCKER_IMAGE}"
    depends_on: ["wavs"]
    stop_signal: SIGKILL
    env_file: "../.env"
    command: ["wavs-aggregator", "--home", "/wavs-home"]
    volumes:
      - "${COMPOSE_WAVS_HOME}:/wavs-home"
    network_mode: "host"
