global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'wavs'
    static_configs:
      - targets: ['localhost:8000']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'wavs-aggregator'
    static_configs:
      - targets: ['localhost:8001']
    scrape_interval: 5s
    metrics_path: /metrics