version: "3"

vars:
  ANVIL_RPC_URL: "https://1rpc.io/holesky"
  ANVIL_PORT: 8545
  WAVS_PORT: 8123
  WAVS_AGGREGATOR_PORT: 8124
  DOCKER_SUDO:
    sh: |
      if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then 
        echo ""
      else 
        echo "sudo"
      fi

env:
  ANVIL_RPC_URL: "{{.ANVIL_RPC_URL}}"
  ANVIL_PORT: "{{.ANVIL_PORT}}"

tasks:
  start:
    desc: "Starts all backend services"
    deps: [start-inner, wait-anvil, wait-wavs, wait-aggregator]

  stop:
    desc: "Stops all backend services"
    dir: backend
    cmds:
      - |
        {{.DOCKER_SUDO}} docker compose --file docker-compose.yml down --remove-orphans || true

  # Internal subtasks

  start-inner:
    internal: true
    dir: backend
    cmds:
      - |
        {{.DOCKER_SUDO}} docker compose --file docker-compose.yml pull
      - |
        {{.DOCKER_SUDO}} docker compose --file docker-compose.yml up --force-recreate -d

  wait-anvil:
    internal: true
    cmds:
      - |
        while ! nc -z localhost {{.ANVIL_PORT}}; do
          echo "Waiting for Anvil to start on port {{.ANVIL_PORT}}..."
          sleep 1
        done
      - echo "Anvil is up and running!"

  wait-wavs:
    internal: true
    cmds:
      - |
        while ! nc -z localhost {{.WAVS_PORT}}; do
          echo "Waiting for WAVS to start on port {{.WAVS_PORT}}..."
          sleep 1
        done
      - echo "WAVS is up and running!"

  wait-aggregator:
    internal: true
    cmds:
      - |
        while ! nc -z localhost {{.WAVS_AGGREGATOR_PORT}}; do
          echo "Waiting for Aggregator to start on port {{.WAVS_AGGREGATOR_PORT}}..."
          sleep 1
        done
      - echo "WAVS Aggregator is up and running!"
