[package]
name = "wavs-llm"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
wavs-wasi-utils = { workspace = true }
wit-bindgen = { workspace = true }
wstd = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
wit-bindgen-rt = { workspace = true, features = ["bitflags"] }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true, features = ["serde"] }
alloy-json-abi = { workspace = true }
alloy-dyn-abi = { workspace = true }
alloy-network = { workspace = true }
alloy-provider = { workspace = true }
alloy-rpc-types = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
tiny-keccak = { workspace = true }
thiserror = { workspace = true }
schemars = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }

[features]
integration-tests = []

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
