[package]
name = "wavs-merkle-sources"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
wavs-wasi-utils = { workspace = true }
wit-bindgen = { workspace = true }
wstd = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
wit-bindgen-rt = { workspace = true, features = ["bitflags"] }
alloy-sol-macro = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-dyn-abi = { workspace = true }
alloy-network = { workspace = true }
alloy-provider = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-contract = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
wavs-indexer-api = { workspace = true }
futures = { workspace = true }
merkle-tree-rs ={ workspace = true }


[dev-dependencies]
mockall = { workspace = true }

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
