version: "3"


env:
  WAVS_DOCKER_IMAGE: "ghcr.io/lay3rlabs/wavs:0.4.0-rc"
  MIDDLEWARE_DOCKER_IMAGE: "ghcr.io/lay3rlabs/wavs-middleware:0.4.0-rc"
  WAVS_PORT: 8123
  ANVIL_PORT: 8548

vars:
  DOCKER_SUDO:
    sh: |
      if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then 
        echo ""
      else 
        echo "sudo"
      fi

tasks:
  wavs:
    desc: "Runs WAVS CLI commands"
    vars:
      REPO_ROOT: "{{joinPath .TASKFILE_DIR \"..\"}}"
      WAVS_HOME: "{{joinPath .REPO_ROOT \"backend/wavs-home\"}}"
      WAVS_ENDPOINT: "http://localhost:{{.WAVS_PORT}}"
    cmds: 
      - >
        {{.DOCKER_SUDO}} docker run --rm --network host
        -v {{.REPO_ROOT}}:/wavs-tools
        -v {{.WAVS_HOME}}:/wavs-home 
        {{.WAVS_DOCKER_IMAGE}}
        wavs-cli {{.CLI_ARGS}} --json true --home /wavs-home --wavs-endpoint {{.WAVS_ENDPOINT}}

  middleware-deploy:
    desc: "Deploy middleware"
    vars:
      REPO_ROOT: "{{joinPath .TASKFILE_DIR \"..\"}}"
    env:
      METADATA_URI: "{{.MIDDLEWARE_METADATA_URI}}"
      FUNDED_KEY: "{{.MIDDLEWARE_FUNDED_KEY}}"
      DEPLOY_ENV: "LOCAL"
      LOCAL_ETHEREUM_RPC_URL: "http://localhost:{{.ANVIL_PORT}}"
    cmds: 
      - >
        {{.DOCKER_SUDO}} docker run --rm --network host
        -e METADATA_URI
        -e FUNDED_KEY
        -e DEPLOY_ENV 
        -e LOCAL_ETHEREUM_RPC_URL
        -v {{.REPO_ROOT}}:/wavs-tools
        {{.MIDDLEWARE_DOCKER_IMAGE}} deploy