version: "3"

dotenv: ["../../.env"]

includes:
  cli: ../../Taskfile-cli.yml

silent: true

vars:
  CHAIN_ID: "{{ .ENV.CHAIN_ID }}"
  COMPONENT_NAME: avs_sync
  COMPONENTS_CARGO_RELEASE_DIR: '{{joinPath .ROOT_DIR "../../target/wasm32-wasip1/release"}}'
  ANVIL_PORT: 8548
  EVM_RPC_URL: "http://localhost:{{.ANVIL_PORT}}"
  MIDDLEWARE_NODES_DIR: '{{joinPath .ROOT_DIR "../../.middleware-nodes"}}'
  SUBMISSION_DEPLOY_SCRIPT: "Deploy.s.sol"
  SERVICE_MANAGER_ADDRESS:
    sh: jq -r '.addresses.WavsServiceManager // empty' "{{.MIDDLEWARE_NODES_DIR}}/avs_deploy.json" || true
  STAKE_REGISTRY_ADDRESS:
    sh: jq -r '.addresses.stakeRegistry // empty' "{{.MIDDLEWARE_NODES_DIR}}/avs_deploy.json" || true

tasks:
  components-build:
    desc: "Builds the WASI component for AVS Sync"
    dir: component
    vars:
      COMPONENTS_DIR: "{{.ROOT_DIR}}/.wasi-output"
    cmds:
      - |
        echo "Building component: {{.COMPONENT_NAME}}"
        cargo component build --release
        mkdir -p {{.COMPONENTS_DIR}}
        cp "{{.COMPONENTS_CARGO_RELEASE_DIR}}/{{.COMPONENT_NAME}}.wasm" {{.COMPONENTS_DIR}}/

  components-upload:
    desc: "Uploads the WASI component for AVS Sync"
    vars:
      # here it's relative to docker volume mount, where /wavs-tools is the root of this repo
      COMPONENTS_DIR: "/wavs-tools/tools/avs-sync/.wasi-output"
      DATA_DIR: "/wavs-tools/tools/avs-sync/.wavs-cli-data"
    cmds:
      # unfortunately, the wavs-cli upload-component command doesn't write to JSON
      # but, fortunately, the last line of the output is the digest
      - |
        OUTPUT=$(task cli:upload-component -- "{{.COMPONENTS_DIR}}/{{.COMPONENT_NAME}}.wasm" --data "{{.DATA_DIR}}")
        DIGEST=$(echo "$OUTPUT" | tail -n 1)
        if [[ "$OUTPUT" == *"Digest"* ]]; then
          echo "Component uploaded successfully, digest is $DIGEST"
          echo "$DIGEST" > "./.wasi-output/component_digest.txt"
        else
          echo "Failed to upload component."
          exit 1
        fi

  contracts-deploy:
    desc: "Deploys the AVS Sync contracts"
    dir: contracts
    vars:
      SCRIPT_NAME: "DeployAvsWriter"
    env:
      SERVICE_MANAGER_ADDRESS: "{{.SERVICE_MANAGER_ADDRESS}}"
      STAKE_REGISTRY_ADDRESS: "{{.STAKE_REGISTRY_ADDRESS}}"
    cmds:
      - forge script script/{{.SUBMISSION_DEPLOY_SCRIPT}}:{{.SCRIPT_NAME}} --broadcast --rpc-url "{{.EVM_RPC_URL}}" --private-key $DEPLOYER_PRIVATE_KEY

  contracts-test:
    desc: "Runs tests for the AVS Sync contracts"
    dir: contracts
    cmds:
      - forge test -vv

  submission-address:
    vars:
      CONTRACT_NAME: "AvsWriter"
    cmds:
      - >
        jq -r '.transactions[] | select(.contractName == "{{.CONTRACT_NAME}}") | .contractAddress // empty'
        "./contracts/broadcast/{{ .SUBMISSION_DEPLOY_SCRIPT }}/$CHAIN_ID/run-latest.json"
