version: "3"

vars:
  COMPONENT_NAME: avs_sync
  COMPONENT_FILENAME: avs_sync.wasm
  PKG_NAME: avssync
  PKG_VERSION: 0.1.0
  BLOCK_INTERVAL: 100
  PAST_BLOCKS: 50000
  # Post-deployment vars
  RPC_URL: http://localhost:8545
  SERVICE_JSON: .docker/service.json
  SERVICE_MANAGER:
    sh: jq -r .addresses.WavsServiceManager ./.nodes/avs_deploy.json

tasks:
  wasi-build:
    cmds:
      - |
        echo "Building component: {{.COMPONENT_NAME}}"
        cargo component build --release; cargo fmt
        mkdir -p ./compiled
        cp target/wasm32-wasip1/release/*.wasm ./compiled

  deploy:
    desc: "Deploy component"
    cmds:
      - chmod +x ./script/deploy-component.sh
      - |
        export COMPONENT_NAME={{.COMPONENT_NAME}}
        export COMPONENT_FILENAME={{.COMPONENT_FILENAME}}
        export PKG_NAME={{.PKG_NAME}}
        export PKG_VERSION={{.PKG_VERSION}}
        export BLOCK_INTERVAL={{.BLOCK_INTERVAL}}
        export PAST_BLOCKS={{.PAST_BLOCKS}}
        ./script/deploy-component.sh

  trigger:
    desc: "Trigger the component"
    cmds:
      - cast rpc anvil_mine {{.CLI_ARGS}} --rpc-url http://localhost:8545

  # Operator State Queries
  list-operator:
    cmds:
      - |
        export PAST_BLOCKS={{.CLI_ARGS}}
        export WAVS_SERVICE_MANAGER_ADDRESS={{.SERVICE_MANAGER}}
        task wavs-middleware -- list_operator
