version: "3"

dotenv: ["../../.env"]

includes:
  cli: ../../taskfile/cli.yml
  middleware: ../../taskfile/middleware.yml
  backend: ../../taskfile/backend.yml
  component: ../../taskfile/component.yml
  config:
    taskfile: ../../taskfile/config.yml
    flatten: true
  test: taskfile/test.yml
  bootstrap: taskfile/bootstrap.yml
  utils:
    taskfile: taskfile/utils.yml
    flatten: true

silent: true

vars:
  # These are all locally defined here, do not depend on config.yml being loaded first
  # For this reason, we sometimes need to redefined vars like .project-output here
  # see: https://github.com/go-task/task/issues/2303
  COMPONENT_NAME: "avs_sync"
  PROJECT:
    # project name is same as dir name of current directory
    sh: basename "$(pwd)"
  BLOCK_INTERVAL: 100
  PAST_BLOCKS: 500
  SUBMISSION_DEPLOY_SCRIPT: "Deploy.s.sol"
  WAVS_CLI_SERVICE_JSON_PATH: "/wavs-tools/projects/avs-sync/.project-output/services/{{.COMPONENT_NAME}}.json"
  PROJECT_OUTPUT_DIR: '{{joinPath .ROOT_DIR ".project-output"}}'
  SERVICE_OUTPUT_DIR: '{{joinPath .PROJECT_OUTPUT_DIR "services"}}'
  SERVICE_JSON_PATH: "{{.SERVICE_OUTPUT_DIR}}/{{.COMPONENT_NAME}}.json"
  # This isn't included in the middleware json
  STRATEGY_MANAGER_ADDRESS: "0xdfB5f6CE42aAA7830E94ECFCcAd411beF4d4D5b6"

tasks:
  bootstrap:
    desc: "A full deployment"
    deps: [clean]
    cmds:
      - |
        task bootstrap:middleware-deploy
        task bootstrap:components-build
        task bootstrap:components-upload
        task bootstrap:contracts-deploy
        task bootstrap:build-service
        task bootstrap:upload-service
        task bootstrap:set-service-uri
        task bootstrap:register-service-uri
        task bootstrap:deploy-service
        task bootstrap:register-operator

  clean:
    desc: "Cleans up the AVS Sync tool"
    deps: [clean-output]
    cmds:
      - rm -rf "contracts/broadcast"
      - rm -rf "contracts/cache"
      - rm -rf "contracts/out"
      - cd "{{.REPO_ROOT}}" && cargo clean -p avs-sync

  clean-output:
    desc: "Cleans up the AVS Sync output directory but not contracts or components"
    cmds:
      - rm -rf "{{.PROJECT_OUTPUT_DIRNAME}}"

  run-tests:
    desc: "Run all test cases"
    cmds:
      - task test:simple
