[profile.default]
src = 'src'
out = 'out'
libs = ['../lib']
solidity_version = '0.8.27'
evm_version = 'shanghai'
via_ir = true
fs_permissions = [{ access = "read-write", path = "./" }]

remappings = [
    "@eigenlayer-middleware/=../lib/eigenlayer-middleware/",
    "forge-std/=../lib/forge-std/src/",
    "@wavs=../node_modules/@wavs/solidity/contracts",
]
