[profile.default]
src = 'src'
out = 'out'
libs = ['../submodules']
solidity_version = '0.8.27'
evm_version = 'shanghai'
via_ir = true
fs_permissions = [{ access = "read-write", path = "./" }]

remappings = [
    "@eigenlayer-middleware/=../submodules/eigenlayer-middleware/",
    "forge-std/=../submodules/forge-std/src/",
    "@openzeppelin/contracts/=../submodules/openzeppelin-contracts/contracts/",
    "@wavs=../submodules/wavs/contracts/solidity",
]
