version: "3"

tasks:
  wasi-build:
    cmds:
      - |
        echo "Building component: avs_sync"
        cargo component build --release; cargo fmt
        mkdir -p {{.COMPONENTS_DIR}}
        cp target/wasm32-wasip1/release/*.wasm {{.COMPONENTS_DIR}}
  deploy:
    cmds:
      - |
        task setup
        cd avs_sync
        forge script script/DeployAvsWriter.s.sol --rpc-url $(../script/get-rpc.sh) --broadcast
        cd ..
  deploy-service:
    deps: ["wasi-build"]
    cmds:
      - |
        export COMPONENT_FILENAME=avs_sync.wasm
        export PKG_NAME="avssync"
        export PKG_VERSION="0.1.0"
        source script/upload-to-wasi-registry.sh || true
        export AGGREGATOR_URL=http://127.0.0.1:8001
        REGISTRY=${REGISTRY} source ./avs_sync/script/build-service.sh
