version: "3"

vars:
  COMPONENT_NAME: avs_sync
  COMPONENT_FILENAME: avs_sync.wasm
  PKG_NAME: avssync
  PKG_VERSION: 0.1.0

tasks:
  wasi-build:
    cmds:
      - |
        echo "Building component: {{.COMPONENT_NAME}}"
        cargo component build --release; cargo fmt
        mkdir -p ./compiled
        cp target/wasm32-wasip1/release/*.wasm ./compiled

  deploy:
    desc: "Deploy component"
    cmds:
      - chmod +x ./script/deploy-component.sh
      - |
        export COMPONENT_NAME={{.COMPONENT_NAME}}
        export COMPONENT_FILENAME={{.COMPONENT_FILENAME}}
        export PKG_NAME={{.PKG_NAME}}
        export PKG_VERSION={{.PKG_VERSION}}
        ./script/deploy-component.sh
