name: Tests
on:
  issue_comment:
    types: [created]

jobs:
  handle-comment:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/test-results')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version: 21

      - name: Install test dependencies
        run: npm ci
        working-directory: tests

      - name: Run tests and generate report
        run: npm run test:report
        working-directory: tests
        continue-on-error: true

      - name: Comment PR with test results
        uses: actions/github-script@v7
        with:
          script: |
            const { commentTestResults } = require('./.github/scripts/comment-test-results.js');
            await commentTestResults({ github, context });
